<a href="https://colab.research.google.com/github/matheus-cmc/atividades_IA_industrial/blob/main/lab03_Atividade1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Visão geral

Este laboratório não continua o cenário do prestador de serviços de saúde. Em vez disso, você trabalhará com dados de um [conjunto de dados (dataset) de automóveis] ( https://archive.ics.uci.edu/ml/datasets/Automobile).

Neste laboratório, você vai:

- Codificar dados categóricos ordinais
- Codificar dados categóricos não ordinais

## Sobre esse conjunto de dados (dataset)

Este conjunto de dados (dataset) consiste em três tipos de entidades:

1. A previsão de um automóvel em termos de suas várias características
2. Sua classificação de risco de seguro atribuído
3. Suas perdas normalizadas em uso em comparação com outros carros

A segunda classificação corresponde ao grau em que o veículo tem associado um risco maior daquele que o seu preço indica. Inicialmente, é atribuído aos carros um símbolo correspondente ao fator de risco associado ao seu preço. Em seguida, se indicar um risco maior (ou menor), esse símbolo será ajustado a sua escala para cima (ou para baixo). Atuários chamam esse processo de *simbologia* . Um valor *+3* indica que o carro tem um risco maior. Um valor de *-3* indica que o carro provavelmente está seguro.

O terceiro fator é a média anual de pagamento de perdas por veículo seguro. Esse valor é normalizado para todos os carros dentro de uma classificação de tamanho específico (duas portas pequenas, peruas, esportivas ou especializadas, entre outros). Representa a perda média por carro por ano.

**Observação:** Vários atributos no banco de dados podem ser usados ​​como um atributo *class* (classe).

## Informações de atributo

Atributo: Intervalo de atributos

1. simbologia: -3, -2, -1, 0, 1, 2, 3.
1. perdas normalizadas: contínuas de 65 a 256.
1. tipo de combustível: gasolina.
1. aspiração: std, turbo.
1. número de portas: quatro, duas.
1. estilo da carroceria: teto rígido, wagon, sedan, hatchback, conversível.
1. tração: 4x4, dianteira, traseira.
1. localização do motor: dianteira, traseira.
1. distância entre os eixos: valor contínuo entre 86,6 e 120,9.
1. tamanho: contínuo de 141,1 a 208,1.
1. largura: contínua de 60,3 a 72,3.
1. altura: contínua de 47,8 a 59,8.
1. peso livre: valor contínuo entre 1488 e 4066.
1. tipo de motor: dohc, dohcv, l, ohc, ohcf, ohcv, rotor.
1. número de cilindros: oito, cinco, quatro, seis, três, doze, dois.
1. tamanho do motor: contínuo de 61 a 326.
1. sistema de combustível: 1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi.
1. diâmetro: contínuo de 2,54 a 3,94.
1. Escutar: valor contínuo entre 2,07 e 4,17.
1. taxa de atualização: valor contínuo entre 7 e 23.
1. potência: contínua de 48 a 288.
1. pico-rpm (rotação -pico): valor contínuo entre 4150 e 6600.
1. mpg-cidade (consumo-cidade): contínuo de 13 a 49.
1. mpg-estrada (consumo-estrada): valor contínuo entre 16 e 54.
1. preço: contínuo de 5118 a 45400.

## Atribuições do conjunto de dados (dataset)

Esse conjunto de dados (dataset) foi obtido de:
Dua, D. e Graff, C. (2019). repositório UCI Machine Learning ( http://archive.ics.uci.edu/ml). Irvine, CA: Universidade da Califórnia, Escola de Informação e Ciência da Computação.

Etapa 01:Como importar e explorar os dados

In [ ]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [ ]:
url = "imports-85.csv"
col_names=['symboling','normalized-losses', 'make', 'fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','wheel-base',
                                    'length','width','height','curb-weight','engine-type','num-of-cylinders','engine-size',
                                    'fuel-system','bore','stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price']

df_car = pd.read_csv(url, sep=',', names=col_names, na_values="?", header=None)

In [ ]:
df_car.shape

(205, 26)

In [ ]:
df_car.head()

   symboling  normalized-losses         make fuel-type aspiration num-of-doors   body-style drive-wheels engine-location  wheel-base  length  width  height  curb-weight engine-type num-of-cylinders  engine-size fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price
0          3                NaN  alfa-romero       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  13495.0
1          3                NaN  alfa-romero       gas        std          two  convertible          rwd           front        88.6   168.8   64.1    48.8         2548        dohc             four          130        mpfi  3.47    2.68                9.0       111.0    5000.0        21           27  16500.0
2          1                NaN  alfa-romero       gas        std          two    hatchback          rwd           front        94.5   171.2   65.5    52.4         2823        ohcv              six          152        mpfi  2.68    3.47                9.0       154.0    5000.0        19           26  16500.0
3          2              164.0         audi       gas        std         four        sedan          fwd           front        99.8   176.6   66.2    54.3         2337         ohc             four          109        mpfi  3.19    3.40               10.0       102.0    5500.0        24           30  13950.0
4          2              164.0         audi       gas        std         four        sedan          4wd           front        99.4   176.6   66.4    54.3         2824         ohc             five          136        mpfi  3.19    3.40                8.0       115.0    5500.0        18           22  17450.0

In [ ]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak-rpm           203 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [ ]:
df_car = df_car[[ 'aspiration', 'num-of-doors',  'drive-wheels',  'num-of-cylinders']].copy()

A maioria dos algoritmos de Machine Learning exige entradas que sejam valores numéricos.

- Os componentes (features) **num-of-cylinders** (número de cilindros) e **num-of-doors** (número de portas) são variáveis ordinais. Você pode converter os valores desses componentes (features) em suas contrapartes numéricas.
- No entanto, **aspiration** e **drive-wheels (tração) ** não têm um valor ordinal. Esses recursos devem ser convertidos de forma diferente.

Você explorará os componentes (features) com valores numéricos primeiro.

# Etapa 2: Codificação de componentes (features) ordinais.

Nesta etapa, você usará a função *mapper* para converter os componentes (features) ordinais em valores numéricos ordenados.

Comece obtendo do DataFrame os novos tipos associados às colunas:

In [ ]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   aspiration        205 non-null    object
 1   num-of-doors      203 non-null    object
 2   drive-wheels      205 non-null    object
 3   num-of-cylinders  205 non-null    object
dtypes: object(4)
memory usage: 6.5+ KB

In [ ]:
df_car['num-of-doors'].value_counts()

num-of-doors
four    114
two      89
Name: count, dtype: int64

In [ ]:
door_mapper = {
    "two" : 2,
    "four": 4
    }

In [ ]:
df_car['doors'] = df_car['num-of-doors'].replace(door_mapper)

/tmp/ipython-input-2302680719.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_car['doors'] = df_car['num-of-doors'].replace(door_mapper)

In [ ]:
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors
0        std          two          rwd             four    2.0
1        std          two          rwd             four    2.0
2        std          two          rwd              six    2.0
3        std         four          fwd             four    4.0
4        std         four          4wd             five    4.0

In [ ]:
df_car['num-of-cylinders'].value_counts(ascending=True)

num-of-cylinders
three       1
twelve      1
two         4
eight       5
five       11
six        24
four      159
Name: count, dtype: int64

In [ ]:
cylinder_mapper = {
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'eight': 8,
    'twelve': 12
}

In [ ]:
df_car['cylinders'] = df_car['num-of-cylinders'].replace(cylinder_mapper)

/tmp/ipython-input-2926988077.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_car['cylinders'] = df_car['num-of-cylinders'].replace(cylinder_mapper)

In [ ]:
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors  cylinders
0        std          two          rwd             four    2.0          4
1        std          two          rwd             four    2.0          4
2        std          two          rwd              six    2.0          6
3        std         four          fwd             four    4.0          4
4        std         four          4wd             five    4.0          5

# Etapa 3: Como codificar dados categóricos não ordinais

Nesta etapa, você codificará dados não ordinais usando o método `get_dummies` do pandas.

Os dois recursos restantes não são ordinais.

De acordo com a descrição do atributo, os seguintes valores são possíveis:

- aspiração: std, turbo.
- tração: 4wd, fwd, rwd.

Você pode pensar que a estratégia correta é converter esses valores em valores numéricos. Por exemplo, considere o recurso **drive-wheels** (tração). Você pode usar *4wd = 1*,*fwd = 2* e *rwd = 3*. No entanto,* fwd* não é menor que *rwd*. Esses valores não têm uma ordem, mas você acabou de introduzir uma ordem a eles atribuindo esses valores numéricos.

A estratégia correta é converter esses valores em *componentes (features) binários* para cada valor no componente (feature) original. Esse processo geralmente é chamado de *one-hot encoding* (codificação distribuída) em Machine Learning ou *dummying* em estatísticas.

O pandas fornece um método `get_dummies`, que converte os dados em componentes (features) binários. Para obter mais informações, consulte [pandas.get_dumisto] (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html) na documentação de pandas.

In [ ]:
df_car.head()

  aspiration num-of-doors drive-wheels num-of-cylinders  doors  cylinders
0        std          two          rwd             four    2.0          4
1        std          two          rwd             four    2.0          4
2        std          two          rwd              six    2.0          6
3        std         four          fwd             four    4.0          4
4        std         four          4wd             five    4.0          5

In [ ]:
df_car['drive-wheels'].value_counts()

drive-wheels
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64

In [ ]:
df_car = pd.get_dummies(df_car, columns=['drive-wheels'])

In [ ]:
df_car.head()

  aspiration num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd
0        std          two             four    2.0          4             False             False              True
1        std          two             four    2.0          4             False             False              True
2        std          two              six    2.0          6             False             False              True
3        std         four             four    4.0          4             False              True             False
4        std         four             five    4.0          5              True             False             False

In [ ]:
df_car.head()

  aspiration num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd
0        std          two             four    2.0          4             False             False              True
1        std          two             four    2.0          4             False             False              True
2        std          two              six    2.0          6             False             False              True
3        std         four             four    4.0          4             False              True             False
4        std         four             five    4.0          5              True             False             False

In [ ]:
df_car['aspiration'].value_counts()

aspiration
std      168
turbo     37
Name: count, dtype: int64

In [ ]:
df_car = pd.get_dummies(df_car,columns=['aspiration'], drop_first=True)

In [ ]:
df_car.head()

  num-of-doors num-of-cylinders  doors  cylinders  drive-wheels_4wd  drive-wheels_fwd  drive-wheels_rwd  aspiration_turbo
0          two             four    2.0          4             False             False              True             False
1          two             four    2.0          4             False             False              True             False
2          two              six    2.0          6             False             False              True             False
3         four             four    4.0          4             False              True             False             False
4         four             five    4.0          5              True             False             False             False